---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU VPC targeting an existing VPC and subnets that are not managed by mu
Parameters:
  Namespace:
    Type: String
    Description: Namespace for stack prefixes
  EnvironmentName:
    Type: String
    Description: Name of environment used for resource namespace
  VpcId:
    Description: VPC to target
    Type: String
  InstanceSubnetIds:
    Description: EC2 subnet ids
    Type: CommaDelimitedList
  ElbSubnetIds:
    Description: ELB subnet ids
    Type: CommaDelimitedList
  AZCount:
    Description: Number of availability zones to use
    Type: String
    Default: '3'
Resources:
  WaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"
Outputs:
  VpcId:
    Description: The id of the vpc
    Value: !Ref VpcId
    Export:
      Name: !Sub ${AWS::StackName}-VpcId
  InstanceSubnetIds:
    Description: The EC2 subnetids
    Value:
      Fn::Join:
      - ','
      - !Ref InstanceSubnetIds
    Export:
      Name: !Sub ${AWS::StackName}-InstanceSubnetIds
  ElbSubnetIds:
    Description: The ELB subnetids
    Value:
      Fn::Join:
      - ','
      - !Ref ElbSubnetIds
    Export:
      Name: !Sub ${AWS::StackName}-ElbSubnetIds
